### ISSUE TITLE
How do I actually use this?

### ISSUE THREAD

**Issue by OfficialCRUGG** [friendlyhj/ProbeZS#12]
Currently working on a Modpack and tried to use the "ZenScript IntelliSense" Visual Studio Code extension which led me here and told me to install this, but how do I actually use it.
I tried using the latest GitHub Release with Forge 1.20.1 and the jar file is just completely ignored. No crash, no log in console, no nothing.
Am I just using a too new build? If yes, which one should I use?

**Comment by friendlyhj** [comment]
It only targets at MC 1.12.2

**Comment by OfficialCRUGG** [comment]
Oh, and there are no plans to target higher versions?
Perhaps it might be useful to indicate this in the Readme somehow?
