### ISSUE TITLE
补全不正常

### ISSUE THREAD

**Issue by 2929762171** [friendlyhj/ProbeZS#13]
如图
![image](https://github.com/user-attachments/assets/53982a05-91cf-4587-ac32-3ce5cd92c2bb)
![image](https://github.com/user-attachments/assets/62fb9c1e-2c88-48d9-8533-fb9cc34df2e0)
![image](https://github.com/user-attachments/assets/04657a4c-b15c-48c5-b68f-897a23bef9a7)

**Comment by friendlyhj** [comment]
插件问题去 https://github.com/raylras/zenscript-intelli-sense
但现在这个插件已经废弃，正在重写 https://github.com/intellizen-dev/intellizen
