### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by l4ssc** [friendlyhj/ProbeZS#9]
log: https://mclo.gs/ehQz5Vb
not sure what exactly is causing this

**Comment by friendlyhj** [comment]
The log is truncated, please post crash report

**Comment by l4ssc** [comment]
[crash-2024-05-17_15.49.19-client.txt](https://github.com/friendlyhj/ProbeZS/files/15359591/crash-2024-05-17_15.49.19-client.txt)

**Comment by friendlyhj** [comment]
It *should* avoid the crash, but I still don't know what caused it. Can you download the latest release, and post `crafttweaker.log` here?
